/robot1/ro_slam_py:
  ros__parameters:
    frame_local: robot1/base_footprint
    frame_odom: robot1/odom
    robot_color: [1.0, 0.0, 0.0]
    show_tags_var: false
    wheel_radius: 0.033
    wheels_separation: 0.16

/robot2/ro_slam_py:
  ros__parameters:
    frame_local: robot2/base_footprint
    frame_odom: robot2/odom
    robot_color: [0.0, 1.0, 0.0]
    show_tags_var: false
    wheel_radius: 0.033
    wheels_separation: 0.16

/robot3/ro_slam_py:
  ros__parameters:
    frame_local: robot3/base_footprint
    frame_odom: robot3/odom
    robot_color: [0.0, 0.0, 1.0]
    show_tags_var: false
    wheel_radius: 0.033
    wheels_separation: 0.16

/robot4/ro_slam_py:
  ros__parameters:
    frame_local: robot4/base_footprint
    frame_odom: robot4/odom
    robot_color: [1.0, 1.0, 0.0]
    show_tags_var: false
    wheel_radius: 0.033
    wheels_separation: 0.16

/robot5/ro_slam_py:
  ros__parameters:
    frame_local: robot5/base_footprint
    frame_odom: robot5/odom
    robot_color: [1.0, 0.0, 1.0]
    show_tags_var: false
    wheel_radius: 0.033
    wheels_separation: 0.16

/robot6/ro_slam_py:
  ros__parameters:
    frame_local: robot6/base_footprint
    frame_odom: robot6/odom
    robot_color: [0.0, 1.0, 1.0]
    show_tags_var: false
    wheel_radius: 0.033
    wheels_separation: 0.16