/joy2cmdvel:
  ros__parameters:
    cmd_vel_topic_name: /robot1/cmd_vel
    joy_topic_name: /joystick/cmd_joystick
    max_ang_vel: 2.0  # rad/s # 2.8 max angular velocity for turtlebot3
    max_lin_vel: 0.22  # m/s