# Joystick message.
#
# Lorenzo Bianchi <lnz.bnc@gmail.com>
#
# February 10, 2023

# This is free software.
# You can redistribute it and/or modify this file under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This file is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this file; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

# Flags
bool connected

# Buttons
int8 cross
int8 circle
int8 square
int8 triangle
int8 l1
int8 r1
int8 share
int8 options
int8 home
int8 l3
int8 r3
int8 extra1
int8 extra2
int8 extra3
int8 extra4
int8 extra5
int8 extra6
int8 extra7

# Axes
float64 lx
float64 ly
float64 l2
float64 rx
float64 ry
float64 r2
float64 dx
float64 dy